parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true
  jest: true

overrides:
- files:
  - src/**/*test.js
  rules:
    max-nested-callbacks:
    - 'off'

extends:
  - 'htmlacademy/node'
  - 'plugin:jest/recommended'

plugins:
  - 'jest'
