services:
  node:
    ports:
      - "80:8080"
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - "$HOME/data/typoteka/logs:/app/logs"
      - "$HOME/data/typoteka/upload:/app/src/express/upload"