version: '3.8'

services:
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "$HOME/data/typoteka/database:/var/lib/postgresql/data"

  node:
    build: .
    environment:
      BACK_PORT: ${BACK_PORT}
      FRONT_PORT: ${FRONT_PORT}
      API_HOST: ${API_HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    ports:
      - "80:8080"
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - "$HOME/data/typoteka/logs:/app/logs"
      - "$HOME/data/typoteka/upload:/app/src/express/upload"