name: Deploy
on: 
  push:
  workflow_dispatch:
defaults:
  run:
    shell: bash -ieo pipefail {0}
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Coping code
        uses: actions/checkout@v3
        with:
          ref: production
          clean: false
      - name: Linting
        run: npm run eslint
      - name: Testing
        run: npm run jest
      - name: Deps installing
        run: npm i 