name: Deploy
on:
  push:
    branches:
      - production
  workflow_dispatch:
defaults:
  run:
    shell: bash -ieo pipefail {0}
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    env:
      BACK_PORT: ${{ vars.BACK_PORT }}
      FRONT_PORT: ${{ vars.FRONT_PORT }}
      API_HOST: ${{ vars.API_HOST }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
    steps:
      - name: Coping code
        uses: actions/checkout@v3
        with:
          ref: production
          clean: false
      - name: Tests
        run: docker compose -f docker-compose-test.yml up --build
      - name: App running
        run: docker compose -f docker-compose.yml -f docker-compose-prod.yml up --build -d