name: Deploy
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Coping code
        uses: actions/checkout@v3
        with:
          ref: production
      - name: test
        run: pwd
