name: Deploy
on:
  push:
  workflow_dispatch:
defaults:
  run:
    shell: bash -ieo pipefail {0}
jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    env:
      BACK_PORT: ${{ env.BACK_PORT }}
      FRONT_PORT: ${{ env.FRONT_PORT }}
      API_HOST: ${{ env.API_HOST }}
      DB_HOST: ${{ env.DB_HOST }}
      DB_PORT: ${{ env.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
    steps:
      - name: Coping code
        uses: actions/checkout@v3
        with:
          ref: github-actions
          clean: false
      - name: Stop previos app version
        run: echo $DB_NAME && docker compose stop
      - name: Linting
        run: npm run eslint
      - name: Deps installing
        run: npm i
      - name: Testing
        run: npm run jest
      - name: App running
        run: docker compose up -d
